### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by marcelaraujo** [vladimirvivien/go-cshared-examples#1]
```
⋊> ~/G/go-cshared-examples on master ⨯ go build -o awesome.so -buildmode=c-shared awesome.go                                                  14:23:25

⋊> ~/G/go-cshared-examples on master ⨯ ll                                                                                                     14:23:35
total 3984
-rw-r--r--   1 marcelaraujo  staff   2.4K Mar  8 14:16 Client.java
-rw-r--r--   1 marcelaraujo  staff   1.0K Mar  8 14:16 LICENSE
-rw-r--r--   1 marcelaraujo  staff    18K Mar  8 14:16 README.md
-rw-r--r--   1 marcelaraujo  staff   419B Mar  8 14:16 awesome.go
-rw-r--r--   1 marcelaraujo  staff   1.4K Mar  8 14:23 awesome.h
-rw-r--r--   1 marcelaraujo  staff   1.9M Mar  8 14:23 awesome.so

⋊> ~/G/go-cshared-examples on master ⨯ node client.js                                                                                         14:20:44
/Users/marcelaraujo/GoProjects/go-cshared-examples/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: dlopen(./awesome.so.dylib, 2): image not found
    at new DynamicLibrary (/Users/marcelaraujo/GoProjects/go-cshared-examples/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/marcelaraujo/GoProjects/go-cshared-examples/node_modules/ffi/lib/library.js:45:12)
    at Object.<anonymous> (/Users/marcelaraujo/GoProjects/go-cshared-examples/client.js:25:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
```

**Comment by vladimirvivien** [comment]
@marcelaraujo thanks for pointing this out.  I wrote the code on Linux and did not test it on Mac OS.  It seems that Nodejs is looking `./awesome.so.dylib` instead of just `./awesome.so`. Hope this https://github.com/joeferner/node-oracle/issues/43 or this https://github.com/nodejs/nan/issues/621 helps with getting the sample to run on your OSX platform.
